HOSTS:
  puppet-master.np-ii-test1:
    roles:
      - master
    platform: el-6-x86_64
    box : centos-65-x64-vbox436-nocm
    box_url : http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-nocm.box
    hypervisor : vagrant
    ip: '10.255.33.135'
  puppet-agent.np-ii-test1:
    roles:
      - default
      - agent
    platform: el-6-x86_64
    box : centos-65-x64-vbox436-nocm
    box_url : http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-nocm.box
    hypervisor : vagrant
    ip: '10.255.33.136'
CONFIG:
  log_level: verbose
  type: foss

